name: Greenframe Analysis
on: [push]
jobs:
  greenframeci:
    runs-on: ubuntu-latest
    name: GreenFrame
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the git history to enable git comparison
          
      - name: Build and test
        run: ./gradlew build
        
      - name: GreenFrame Analysis
        uses: marmelab/greenframe-action@1.0.0
        env:
          GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
