name: Greenframe Analysis
on: [push]
jobs:
  greenframeci:
    runs-on: ubuntu-latest
    name: GreenFrame
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all the git history to enable git comparison
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Start project
        run: |
          make install
          make start
      - name: GreenFrame Analysis
        uses: marmelab/greenframe-action@1.0.0
        env:
          GREENFRAME_SECRET_TOKEN: ${{secrets.GREENFRAME_SECRET_TOKEN}}
